/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.NhaCungCapBUS;
import BUS.SupplierBUS;
import DTO.NhaCungCapDTO;
import DTO.SupplierDTO;
import Design.TableCustom;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class DialogSupplier extends javax.swing.JDialog {
    DefaultTableModel modelSupplier;
    private ArrayList<SupplierDTO> listSupplier;
    private SupplierBUS supBUS = new SupplierBUS();
    public DialogSupplier() {
        setUndecorated(true);
        initComponents();
        this.setModal(true);       
        this.setResizable(false);    
        setLocationRelativeTo(null);
        lbExit.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/exit.png")));
        TableCustom.apply(jScrollPane6, TableCustom.TableType.DEFAULT);
        modelSupplier = (DefaultTableModel) tbTableSupplier.getModel();
        supBUS.readList(); 
        loadData();
       
    }
    private void loadData(){
        listSupplier = supBUS.getListSupplier();
        showAll(listSupplier);
    }
    public void loadSearch(String sql){
        listSupplier = supBUS.getSearch(sql);
        showAll(listSupplier);
    }
    public void showAll(ArrayList<SupplierDTO> listSup) {      
        modelSupplier.setRowCount(0);
        for (int i = 0; i < listSup.size(); i++) {
            modelSupplier.addRow(new String[]{
                listSup.get(i).getMaNCC(),
                listSup.get(i).getTenNCC(),
                listSup.get(i).getDienThoai(),
                listSup.get(i).getDiaChi(),
                listSup.get(i).getSofax()
            });
        }
    }
      public String getMaNhaCungCap(){
        return txtMaNCC.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnHeader1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbExit = new Design.MyLabel_Icon();
        panelBorder18 = new Design.PanelBorder();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbTableSupplier = new javax.swing.JTable();
        panelBorder16 = new Design.PanelBorder();
        attribute52 = new Design.Attribute();
        txtMaNCC = new Design.Text();
        attribute53 = new Design.Attribute();
        txtTenNCC = new Design.Text();
        attribute55 = new Design.Attribute();
        txtDienThoai = new Design.Text();
        attribute56 = new Design.Attribute();
        txtSofax = new Design.Text();
        attribute57 = new Design.Attribute();
        txtDiaChi = new Design.Text();
        panelBorder17 = new Design.PanelBorder();
        ckMaNCC = new javax.swing.JCheckBox();
        ckTenNCC = new javax.swing.JCheckBox();
        btSearch = new Design.MyButtonIcon();
        ckDienThoai = new javax.swing.JCheckBox();
        ckDiaChi = new javax.swing.JCheckBox();
        btChon = new Design.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        pnHeader1.setBackground(new java.awt.Color(153, 153, 153));
        pnHeader1.setPreferredSize(new java.awt.Dimension(102, 40));

        jLabel9.setFont(new java.awt.Font("Baloo 2 ExtraBold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Supplier");

        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnHeader1Layout = new javax.swing.GroupLayout(pnHeader1);
        pnHeader1.setLayout(pnHeader1Layout);
        pnHeader1Layout.setHorizontalGroup(
            pnHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeader1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnHeader1Layout.setVerticalGroup(
            pnHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeader1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeader1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelBorder18.setBackground(new java.awt.Color(230, 230, 230));

        tbTableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Điện thoại", "Địa chỉ", "Số fax"
            }
        ));
        tbTableSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTableSupplierMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbTableSupplier);

        javax.swing.GroupLayout panelBorder18Layout = new javax.swing.GroupLayout(panelBorder18);
        panelBorder18.setLayout(panelBorder18Layout);
        panelBorder18Layout.setHorizontalGroup(
            panelBorder18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder18Layout.setVerticalGroup(
            panelBorder18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder16.setBackground(new java.awt.Color(230, 230, 230));

        attribute52.setText("Mã nhà cung cấp");

        txtMaNCC.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute53.setText("Tên nhà cung cấp");

        txtTenNCC.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute55.setText("Điện thoại");

        txtDienThoai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute56.setText("Sofax");

        txtSofax.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute57.setText("Địa chỉ");

        txtDiaChi.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        panelBorder17.setBackground(new java.awt.Color(255, 255, 255));

        ckMaNCC.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckMaNCC.setForeground(new java.awt.Color(0, 0, 0));
        ckMaNCC.setText("Mã nhà cung cấp");

        ckTenNCC.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckTenNCC.setForeground(new java.awt.Color(0, 0, 0));
        ckTenNCC.setText("Tên nhà cung cấp");

        btSearch.setText("Search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        ckDienThoai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 12)); // NOI18N
        ckDienThoai.setForeground(new java.awt.Color(0, 0, 0));
        ckDienThoai.setText("Số điện thoại");

        ckDiaChi.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckDiaChi.setForeground(new java.awt.Color(0, 0, 0));
        ckDiaChi.setText("Địa chỉ");
        ckDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDiaChiActionPerformed(evt);
            }
        });

        btChon.setText("Chọn");
        btChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder17Layout = new javax.swing.GroupLayout(panelBorder17);
        panelBorder17.setLayout(panelBorder17Layout);
        panelBorder17Layout.setHorizontalGroup(
            panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder17Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckMaNCC)
                    .addComponent(ckTenNCC))
                .addGap(24, 24, 24)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckDienThoai)
                    .addComponent(ckDiaChi))
                .addGap(26, 26, 26)
                .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btChon, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        panelBorder17Layout.setVerticalGroup(
            panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder17Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckDienThoai)
                    .addComponent(ckMaNCC))
                .addGap(11, 11, 11)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckTenNCC)
                    .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckDiaChi))
                .addGap(38, 38, 38)
                .addComponent(btChon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBorder16Layout = new javax.swing.GroupLayout(panelBorder16);
        panelBorder16.setLayout(panelBorder16Layout);
        panelBorder16Layout.setHorizontalGroup(
            panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder16Layout.createSequentialGroup()
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attribute52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtTenNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelBorder16Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(attribute55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBorder16Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtSofax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBorder16Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attribute56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(panelBorder17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(panelBorder16Layout.createSequentialGroup()
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attribute57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelBorder16Layout.setVerticalGroup(
            panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder16Layout.createSequentialGroup()
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attribute52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attribute53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSofax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(attribute57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelBorder17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelBorder18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pnHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTableSupplierMouseClicked
        int k = tbTableSupplier.getSelectedRow();
        txtMaNCC.setText(tbTableSupplier.getModel().getValueAt(k, 0).toString());
        txtTenNCC.setText(tbTableSupplier.getModel().getValueAt(k, 1).toString());
        txtDienThoai.setText(tbTableSupplier.getModel().getValueAt(k, 2).toString());
        txtDiaChi.setText(tbTableSupplier.getModel().getValueAt(k, 3).toString());
        txtSofax.setText(tbTableSupplier.getModel().getValueAt(k, 4).toString());
    }//GEN-LAST:event_tbTableSupplierMouseClicked

    private void ckDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckDiaChiActionPerformed

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        dispose();
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered

    }//GEN-LAST:event_lbExitMouseEntered

    private void btChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonActionPerformed

        dispose();

    }//GEN-LAST:event_btChonActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        String sql = "SELECT * FROM NHACUNGCAP WHERE isDelete = 0"; 
        try{
            String MaNCC = txtMaNCC.getText();
            String TenNCC = txtTenNCC.getText();
            String DienThoai = txtDienThoai.getText();
            String DiaChi = txtDiaChi.getText();
             if(ckMaNCC.isSelected()){
                if(MaNCC.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập mã nhà cung cấp cần tìm");
                    return;
                }
                    sql +=" AND MANCC LIKE '%" + MaNCC+ "%'";
            }
            if(ckTenNCC.isSelected()){
                if(TenNCC.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập tên nhà cung cấp cần tìm");
                    return;
                }
                    sql +=" AND TENNCC LIKE '%" + TenNCC + "%'";
            }
            if(ckDienThoai.isSelected()){
                if(DienThoai.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập số điện thoại cần tìm");
                    return;
                }
                if (!DienThoai.matches("\\d{10}")) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Vui lòng nhập đúng định dạng (10 chữ số).");
                    return;
                }
                sql +=" AND DIENTHOAI LIKE '%" + DienThoai+ "%'";
                
            }
            if(ckDiaChi.isSelected()){
                if(DiaChi.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập dia chi cần tìm");
                    return;
                }
                    sql +=" AND DIACHI LIKE '%" + DiaChi + "%'";
            }
            loadSearch(sql);
        } 
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btSearchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Design.Attribute attribute52;
    private Design.Attribute attribute53;
    private Design.Attribute attribute55;
    private Design.Attribute attribute56;
    private Design.Attribute attribute57;
    private Design.MyButton btChon;
    private Design.MyButtonIcon btSearch;
    private javax.swing.JCheckBox ckDiaChi;
    private javax.swing.JCheckBox ckDienThoai;
    private javax.swing.JCheckBox ckMaNCC;
    private javax.swing.JCheckBox ckTenNCC;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private Design.MyLabel_Icon lbExit;
    private Design.PanelBorder panelBorder16;
    private Design.PanelBorder panelBorder17;
    private Design.PanelBorder panelBorder18;
    private javax.swing.JPanel pnHeader1;
    private javax.swing.JTable tbTableSupplier;
    private Design.Text txtDiaChi;
    private Design.Text txtDienThoai;
    private Design.Text txtMaNCC;
    private Design.Text txtSofax;
    private Design.Text txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
