/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.CustomerBUS;
import BUS.NhaCungCapBUS;
import BUS.SupplierBUS;
import DTO.CustomerDTO;
import DTO.NhaCungCapDTO;
import DTO.SupplierDTO;
import Design.TableCustom;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class DialogCustomer extends javax.swing.JDialog {
    DefaultTableModel model;
    private CustomerBUS cusBUS = new CustomerBUS();
    private ArrayList<CustomerDTO> listCustomer;
    public DialogCustomer() {
        setUndecorated(true);
        initComponents();
        this.setModal(true);       
        this.setResizable(false);    
        setLocationRelativeTo(null);
        lbExit.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/exit.png")));
        TableCustom.apply(jScrollPane6, TableCustom.TableType.DEFAULT);
        model = (DefaultTableModel) tbTableCustomer.getModel();
        cusBUS.readList(); 
        loadData();
        
    }
    private void loadData(){
        listCustomer = cusBUS.getListCustomer();
        showAll(listCustomer);
    }
    public void loadSearch(String sql){
        listCustomer = cusBUS.getSearch(sql);
        showAll(listCustomer);
    }
     public void showAll(ArrayList<CustomerDTO> listCus) {      
        model.setRowCount(0);
        for (int i = 0; i < listCus.size(); i++) {
            model.addRow(new String[]{
                listCus.get(i).getMaKH(),
                listCus.get(i).getHoKH(),
                listCus.get(i).getTenKH(),
                listCus.get(i).getGioiTinh(),
                listCus.get(i).getDiaChi(),
                listCus.get(i).getDienThoai(), 
            });
        }
    }
    public String getMaKhachHang(){
        return txtMaKH.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnHeader1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbExit = new Design.MyLabel_Icon();
        panelBorder18 = new Design.PanelBorder();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbTableCustomer = new javax.swing.JTable();
        panelBorder16 = new Design.PanelBorder();
        attribute52 = new Design.Attribute();
        txtMaKH = new Design.Text();
        attribute53 = new Design.Attribute();
        txtHoKH = new Design.Text();
        attribute55 = new Design.Attribute();
        txtDiaChi = new Design.Text();
        attribute56 = new Design.Attribute();
        txtDienThoai = new Design.Text();
        attribute57 = new Design.Attribute();
        txtTenKH = new Design.Text();
        panelBorder17 = new Design.PanelBorder();
        ckMaKH = new javax.swing.JCheckBox();
        ckHoKH = new javax.swing.JCheckBox();
        ckTenKH = new javax.swing.JCheckBox();
        btSearch = new Design.MyButtonIcon();
        ckDienThoai = new javax.swing.JCheckBox();
        ckDiaChi = new javax.swing.JCheckBox();
        btClear = new Design.MyButtonIcon();
        btAdd = new Design.MyButtonIcon();
        btChon = new Design.MyButton();
        attribute58 = new Design.Attribute();
        cbxGioiTinh = new Design.MyComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        pnHeader1.setBackground(new java.awt.Color(102, 102, 102));
        pnHeader1.setPreferredSize(new java.awt.Dimension(102, 40));

        jLabel9.setFont(new java.awt.Font("Dosis ExtraBold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Customer");

        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnHeader1Layout = new javax.swing.GroupLayout(pnHeader1);
        pnHeader1.setLayout(pnHeader1Layout);
        pnHeader1Layout.setHorizontalGroup(
            pnHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeader1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnHeader1Layout.setVerticalGroup(
            pnHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeader1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnHeader1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder18.setBackground(new java.awt.Color(230, 230, 230));

        tbTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "Giới tính ", "Số điện thoại ", "Địa chỉ"
            }
        ));
        tbTableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTableCustomerMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbTableCustomer);

        javax.swing.GroupLayout panelBorder18Layout = new javax.swing.GroupLayout(panelBorder18);
        panelBorder18.setLayout(panelBorder18Layout);
        panelBorder18Layout.setHorizontalGroup(
            panelBorder18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        panelBorder18Layout.setVerticalGroup(
            panelBorder18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder16.setBackground(new java.awt.Color(230, 230, 230));

        attribute52.setText("Mã khách hàng");

        txtMaKH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute53.setText("Họ khách hàng");

        txtHoKH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute55.setText("Giới tính");

        txtDiaChi.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute56.setText("Địa chỉ");

        txtDienThoai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute57.setText("Tên khách hàng");

        txtTenKH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        panelBorder17.setBackground(new java.awt.Color(255, 255, 255));

        ckMaKH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckMaKH.setForeground(new java.awt.Color(0, 0, 0));
        ckMaKH.setText("Mã khách hàng");

        ckHoKH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckHoKH.setForeground(new java.awt.Color(0, 0, 0));
        ckHoKH.setText("Họ khách hàng");

        ckTenKH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckTenKH.setForeground(new java.awt.Color(0, 0, 0));
        ckTenKH.setText("Tên khách hàng");

        btSearch.setText("Search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        ckDienThoai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 12)); // NOI18N
        ckDienThoai.setForeground(new java.awt.Color(0, 0, 0));
        ckDienThoai.setText("Số điện thoại");

        ckDiaChi.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckDiaChi.setForeground(new java.awt.Color(0, 0, 0));
        ckDiaChi.setText("Địa chỉ");
        ckDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDiaChiActionPerformed(evt);
            }
        });

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btChon.setText("Chọn");
        btChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder17Layout = new javax.swing.GroupLayout(panelBorder17);
        panelBorder17.setLayout(panelBorder17Layout);
        panelBorder17Layout.setHorizontalGroup(
            panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder17Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckMaKH)
                    .addComponent(ckHoKH))
                .addGap(24, 24, 24)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckTenKH)
                    .addComponent(ckDienThoai))
                .addGap(37, 37, 37)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckDiaChi)
                    .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBorder17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btChon, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        panelBorder17Layout.setVerticalGroup(
            panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder17Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckDienThoai)
                    .addComponent(ckMaKH)
                    .addComponent(ckDiaChi))
                .addGap(11, 11, 11)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckTenKH)
                    .addComponent(ckHoKH)
                    .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder17Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder17Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btChon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        attribute58.setText("Điện thoại");

        cbxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chọn giới tính", "nữ", "nam", " " }));

        javax.swing.GroupLayout panelBorder16Layout = new javax.swing.GroupLayout(panelBorder16);
        panelBorder16.setLayout(panelBorder16Layout);
        panelBorder16Layout.setHorizontalGroup(
            panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder16Layout.createSequentialGroup()
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attribute52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtHoKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder16Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attribute56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelBorder16Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attribute55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attribute58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribute57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, Short.MAX_VALUE)
                .addComponent(panelBorder17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBorder16Layout.setVerticalGroup(
            panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder16Layout.createSequentialGroup()
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attribute52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attribute53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder16Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(attribute57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBorder16Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(attribute56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelBorder17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pnHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTableCustomerMouseClicked
        int k = tbTableCustomer.getSelectedRow();
        txtMaKH.setText(tbTableCustomer.getModel().getValueAt(k, 0).toString());
        txtHoKH.setText(tbTableCustomer.getModel().getValueAt(k, 1).toString());
        txtTenKH.setText(tbTableCustomer.getModel().getValueAt(k, 2).toString());
        cbxGioiTinh.setSelectedItem(tbTableCustomer.getModel().getValueAt(k, 3).toString());
        txtDienThoai.setText(tbTableCustomer.getModel().getValueAt(k, 4).toString());
        txtDiaChi.setText(tbTableCustomer.getModel().getValueAt(k, 5).toString());
         
        txtMaKH.setEnabled(false);
        txtHoKH.setEnabled(false);
        txtTenKH.setEnabled(false);
        txtDienThoai.setEnabled(false);
        txtDiaChi.setEnabled(false);
    }//GEN-LAST:event_tbTableCustomerMouseClicked

    private void ckDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckDiaChiActionPerformed

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        dispose();
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered

    }//GEN-LAST:event_lbExitMouseEntered

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        txtMaKH.setText("");
        txtHoKH.setText("");
        txtTenKH.setText("");
        cbxGioiTinh.setSelectedItem(0);
        txtDiaChi.setText("");
        txtDienThoai.setText("");
        
        txtMaKH.setEnabled(true);
        txtHoKH.setEnabled(true);
        txtTenKH.setEnabled(true);
        txtDienThoai.setEnabled(true);
        txtDiaChi.setEnabled(true);
        tbTableCustomer.getSelectionModel().clearSelection(); //bỏ chọn Row trong JTable
    }//GEN-LAST:event_btClearActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if (txtMaKH.getText().trim().isEmpty()
            || txtHoKH.getText().trim().isEmpty()
            || txtTenKH.getText().trim().isEmpty()
            || cbxGioiTinh.getSelectedItem().equals("Chọn giới tính")
            || txtDienThoai.getText().trim().isEmpty()
            || txtDiaChi.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please fill in customer information!");
            return;
        }
        if (!txtDienThoai.getText().matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Vui lòng nhập đúng định dạng (10 chữ số).");
            return;
        }
        String MaKH = txtMaKH.getText();
        String HoKH = txtHoKH.getText();
        String TenKH = txtTenKH.getText();
        String DiaChi = txtDiaChi.getText();
        String DienThoai = txtDienThoai.getText();
        String GioiTinh = (String) cbxGioiTinh.getSelectedItem();
        CustomerDTO customer = new CustomerDTO(MaKH, HoKH, TenKH, GioiTinh, DienThoai, DiaChi);
        cusBUS.insert(customer);
        loadData();
    }//GEN-LAST:event_btAddActionPerformed

    private void btChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonActionPerformed
        dispose();
        
    }//GEN-LAST:event_btChonActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
         String sql = "SELECT * FROM KHACHHANG WHERE isDelete = 0"; 
        try{
            String MaKH = txtMaKH.getText();
            String HoKH = txtHoKH.getText();
            String TenKH = txtTenKH.getText();
            String DienThoai = txtDienThoai.getText();
            String DiaChi = txtDiaChi.getText();
            if(ckMaKH.isSelected()){
                if(MaKH.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập mã khách hàng cần tìm");
                    return;
                }
                    sql +=" AND MAKH LIKE '%" + MaKH + "%'";
            }
            if(ckHoKH.isSelected()){
                if(HoKH.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập họ khách hàng cần tìm");
                    return;
                }
                    sql +=" AND HOKH LIKE N'%" + HoKH + "%'";
            }
            if(ckHoKH.isSelected()){
                if(TenKH.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập tên khách hàng cần tìm");
                    return;
                }
                    sql +=" AND TENKH LIKE N'%" + TenKH + "%'";
            }
            if(ckDienThoai.isSelected()){
                if(DienThoai.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập số điện thoại cần tìm");
                    return;
                }
                if (!DienThoai.matches("\\d{10}")) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Vui lòng nhập đúng định dạng (10 chữ số).");
                    return;
                }
                sql +=" AND DIENTHOAI LIKE '%" + DienThoai+ "%'";
                
            }
            if(ckDiaChi.isSelected()){
                if(DiaChi.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập dia chi cần tìm");
                    return;
                }
                    sql +=" AND DIACHI LIKE N'%" + DiaChi + "%'";
            }
            loadSearch(sql);
        } 
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btSearchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Design.Attribute attribute52;
    private Design.Attribute attribute53;
    private Design.Attribute attribute55;
    private Design.Attribute attribute56;
    private Design.Attribute attribute57;
    private Design.Attribute attribute58;
    private Design.MyButtonIcon btAdd;
    private Design.MyButton btChon;
    private Design.MyButtonIcon btClear;
    private Design.MyButtonIcon btSearch;
    private Design.MyComboBox cbxGioiTinh;
    private javax.swing.JCheckBox ckDiaChi;
    private javax.swing.JCheckBox ckDienThoai;
    private javax.swing.JCheckBox ckHoKH;
    private javax.swing.JCheckBox ckMaKH;
    private javax.swing.JCheckBox ckTenKH;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private Design.MyLabel_Icon lbExit;
    private Design.PanelBorder panelBorder16;
    private Design.PanelBorder panelBorder17;
    private Design.PanelBorder panelBorder18;
    private javax.swing.JPanel pnHeader1;
    private javax.swing.JTable tbTableCustomer;
    private Design.Text txtDiaChi;
    private Design.Text txtDienThoai;
    private Design.Text txtHoKH;
    private Design.Text txtMaKH;
    private Design.Text txtTenKH;
    // End of variables declaration//GEN-END:variables
}
