
package GUI;

import Conection.Database;
import Conection.Gmail;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Find_AccountGUI extends javax.swing.JFrame {
    public Find_AccountGUI() {
        initComponents();
        lbThu.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/email.png")));
        lbThongBao.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/chamthan.png")));
        btConfirm.setForeground(Color.WHITE);
        txtUserName.setHint("Enter username");
        txtCode.setHint("Enter code");
        lbThongBao.setVisible(false);
        lbThongBao.setTextColor(Color.RED);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         btConfirm.setColor(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelBorder1 = new Design.PanelBorder();
        lbThu = new Design.MyLabel_Icon();
        btConfirm = new Design.MyButton();
        txtUserName = new Design.MyTextField2();
        txtCode = new Design.MyTextField2();
        lbThongBao = new Design.MyLabel_Icon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find Account\n");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelBorder1.setBackground(new java.awt.Color(200, 200, 200));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbThuMouseEntered(evt);
            }
        });
        panelBorder1.add(lbThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 35, 30));

        btConfirm.setText("Confirm");
        btConfirm.setRadius(20);
        btConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmActionPerformed(evt);
            }
        });
        panelBorder1.add(btConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 110, 30));

        txtUserName.setToolTipText("");
        panelBorder1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 38, 270, 40));
        panelBorder1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 98, 190, 40));
        panelBorder1.add(lbThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 310, 22));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThuMouseEntered
         setCursor(new Cursor(Cursor.HAND_CURSOR));
         lbThu.setToolTipText("Click here to get the code");
    }//GEN-LAST:event_lbThuMouseEntered
    private int MaXacNhan;
    private void lbThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThuMouseClicked
        if(txtUserName.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Username not entered!", "Hello", JOptionPane.OK_CANCEL_OPTION);
              txtUserName.requestFocus(); // di chuyển con trỏ đến ô textfield
        }
        else{
            try{
                    java.sql.Connection conn = new Database().getConnection();
                    String sql = "select Email\n" 
                             + "from NguoiDung\n" 
                             +"where TenDangNhap = ?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, txtUserName.getText());
                    ResultSet rs = ps.executeQuery();
                    if(rs.next()){
                        Gmail gmail = new Gmail();
                        MaXacNhan = ThreadLocalRandom.current().nextInt(100000, 999999);
                        gmail.sendText(rs.getString("Email"), String.valueOf(MaXacNhan));
                        JOptionPane.showMessageDialog(this, "Verification code has been sent to your gmail!!");
                    }
                     else {
                          lbThongBao.setLabelText("Incorrect username");
                          lbThongBao.setVisible(true);
                    }
            }
            catch(Exception e){
                System.out.println("Sending code failed!");
            }
        }
          
    }//GEN-LAST:event_lbThuMouseClicked

    private void btConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmActionPerformed
//        if(txtCode.getText().equals(String.valueOf(MaXacNhan))){
            try {
               Change_PWGUI cp = new Change_PWGUI(txtUserName.getText());
                cp.setVisible(true);
                cp.setLocationRelativeTo(null);
                this.setVisible(false);
            } catch (Exception e) {
                System.out.println(e);
            }
        
//        }
//        else{
//            lbThongBao.setLabelText("Code does not match!");
//            lbThongBao.setVisible(true);
//            txtCode.setText("");
//        }
    }//GEN-LAST:event_btConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Find_AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Find_AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Find_AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Find_AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Find_AccountGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Design.MyButton btConfirm;
    private javax.swing.JPanel jPanel2;
    private Design.MyLabel_Icon lbThongBao;
    private Design.MyLabel_Icon lbThu;
    private Design.PanelBorder panelBorder1;
    private Design.MyTextField2 txtCode;
    private Design.MyTextField2 txtUserName;
    // End of variables declaration//GEN-END:variables
}
