package GUI;

import BUS.CustomerBUS;
import BUS.EmployeeBUS;
import BUS.ProductBUS;
import BUS.SupplierBUS;
import DTO.InformationDTO;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseEvent;
import javaswingdev.drawer.Drawer;
import javaswingdev.drawer.DrawerController;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.miginfocom.layout.ComponentWrapper;

public class Home_Page extends javax.swing.JFrame {

    InformationGUI information = new InformationGUI();
    SupplyGUI supply = new SupplyGUI();
    InvoiceGUI invoice = new InvoiceGUI();
    StatisticsGUI statistics = new StatisticsGUI();
    EmployeeGUI employee = new EmployeeGUI();
    ProductGUI product = new ProductGUI();
    CustomerGUI customer = new CustomerGUI();
    SupplierGUI supplier = new SupplierGUI();

    TrangChu trangchu = new TrangChu();
    CardLayout c = new CardLayout();
    private int DoDai = 0;
    public Home_Page() {
        setUndecorated(true);
        initComponents();

        setVisible(true);
        setLocationRelativeTo(null);
        lbMenu.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/icon-menu.png")));
        lbLogo.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/logo.png")));
        lbExit.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/exit.png")));
        lbInformation.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/supply_records.png")));
        lbEmployee.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/user.png")));
        lbInvoice.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/bill.png")));
        lbCustomer.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/customer.png")));
        lbStatistics.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/line-chart.png")));
        lbSupply.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/order.png")));
        lbProduct.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/product.png")));
        lbLogout.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/logout.png")));
        pnMenu.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        btImport.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/excel.png")));
        btExport.setImage_Icon(new ImageIcon(getClass().getResource("/Hinh/export.png")));

        pnChung.setLayout(c);
        pnChung.add(trangchu, "Trang Chu");
        pnChung.add(information, "Information");
        pnChung.add(supply, "Supply");
        pnChung.add(invoice, "Invoice");
        pnChung.add(statistics, "Statistics");
        pnChung.add(employee, "Employee");
        pnChung.add(product, "Product");
        pnChung.add(customer, "Customer");
        pnChung.add(supplier, "Supplier");
        InformationDTO in = new InformationDTO();
        if (in.getRoleID() == 1){
            this.DoDai = 380;
        }
        else{
            this.DoDai = 210;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnNen = new javax.swing.JPanel();
        pnTieuDe = new javax.swing.JPanel();
        lbMenu = new Design.MyLabel_Icon();
        lbLogo = new Design.MyLabel_Icon();
        lbExit = new Design.MyLabel_Icon();
        pnHomePage = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        lbInformation = new Design.MyLabel_IconRight();
        lbEmployee = new Design.MyLabel_IconRight();
        lbProduct = new Design.MyLabel_IconRight();
        lbCustomer = new Design.MyLabel_IconRight();
        lbSupply = new Design.MyLabel_IconRight();
        lbInvoice = new Design.MyLabel_IconRight();
        lbStatistics = new Design.MyLabel_IconRight();
        lbLogout = new Design.MyLabel_IconRight();
        lbSupplier = new Design.MyLabel_IconRight();
        pnToolBar = new javax.swing.JPanel();
        btExport = new Design.MyButtonIcon();
        btImport = new Design.MyButtonIcon();
        lbHienTai = new javax.swing.JLabel();
        pnChung = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnNen.setBackground(new java.awt.Color(204, 255, 255));
        pnNen.setLayout(new java.awt.BorderLayout());

        pnTieuDe.setBackground(new java.awt.Color(0, 0, 0));

        lbMenu.setBackground(new java.awt.Color(0, 0, 0));
        lbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuMouseExited(evt);
            }
        });

        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnTieuDeLayout = new javax.swing.GroupLayout(pnTieuDe);
        pnTieuDe.setLayout(pnTieuDeLayout);
        pnTieuDeLayout.setHorizontalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuDeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 892, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnTieuDeLayout.setVerticalGroup(
            pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTieuDeLayout.createSequentialGroup()
                .addGroup(pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTieuDeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnTieuDeLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnTieuDeLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnNen.add(pnTieuDe, java.awt.BorderLayout.PAGE_START);

        pnHomePage.setBackground(new java.awt.Color(255, 255, 255));
        pnHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbInformation.setFont(new java.awt.Font("Dosis ExtraBold", 0, 12)); // NOI18N
        lbInformation.setLabelText(" Information");
        lbInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInformationMouseClicked(evt);
            }
        });
        pnMenu.add(lbInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, -1));

        lbEmployee.setLabelText(" Employee");
        lbEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEmployeeMouseClicked(evt);
            }
        });
        pnMenu.add(lbEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 30));

        lbProduct.setLabelText(" Product");
        lbProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbProductMouseClicked(evt);
            }
        });
        pnMenu.add(lbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, -1));

        lbCustomer.setLabelText(" Customer ");
        lbCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCustomerMouseClicked(evt);
            }
        });
        pnMenu.add(lbCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 200, 30));

        lbSupply.setLabelText(" Supply");
        lbSupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSupplyMouseClicked(evt);
            }
        });
        pnMenu.add(lbSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 30));

        lbInvoice.setLabelText(" Invoice");
        lbInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInvoiceMouseClicked(evt);
            }
        });
        pnMenu.add(lbInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 30));

        lbStatistics.setLabelText(" Statistics");
        lbStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbStatisticsMouseClicked(evt);
            }
        });
        pnMenu.add(lbStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 30));

        lbLogout.setLabelText(" Log out");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });
        pnMenu.add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        lbSupplier.setLabelText(" Supplier");
        lbSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSupplierMouseClicked(evt);
            }
        });
        pnMenu.add(lbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 30));

        pnHomePage.add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 0, 370));

        pnToolBar.setBackground(new java.awt.Color(255, 255, 255));

        btExport.setText("Export Excel");
        btExport.setRadius(15);
        btExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportActionPerformed(evt);
            }
        });

        btImport.setText("Import Excel");
        btImport.setRadius(15);

        lbHienTai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 18)); // NOI18N
        lbHienTai.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnToolBarLayout = new javax.swing.GroupLayout(pnToolBar);
        pnToolBar.setLayout(pnToolBarLayout);
        pnToolBarLayout.setHorizontalGroup(
            pnToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnToolBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 622, Short.MAX_VALUE)
                .addComponent(btExport, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btImport, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnToolBarLayout.setVerticalGroup(
            pnToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnToolBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btExport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btImport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbHienTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnHomePage.add(pnToolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 50));

        pnChung.setLayout(new java.awt.CardLayout());
        pnHomePage.add(pnChung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1170, 650));

        pnNen.add(pnHomePage, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void openMenuBar() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < DoDai; i++) {
                    pnMenu.setSize(220, i);
                    try {
                        Thread.sleep(1);
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                }
            }

        }).start();
    }

    public void closeMenuBar() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = DoDai; i > 0; i--) {
                    pnMenu.setSize(220, i);
                    try {
                        Thread.sleep(0);
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                }
            }

        }).start();
    }
    private boolean open = true;
    private void lbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseClicked
//          if (open) {
//              openMenuBar();
//              open = false;
//          }
//          else{
//              closeMenuBar();
//              open = true;
//          }
        openMenuBar();
    }//GEN-LAST:event_lbMenuMouseClicked
    public void HienThi(){
        if(lbHienTai.getText().equals("Information")){
            btExport.setVisible(false);
            btImport.setVisible(false);
        }
        else if(lbHienTai.getText().equals("Product")){
            btExport.setVisible(true);
            btImport.setVisible(true);
        }
        else{
            btExport.setVisible(true);
            btImport.setVisible(false);
        }
    }
    private void lbMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseEntered
        lbMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_lbMenuMouseEntered

    private void lbMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseExited

    }//GEN-LAST:event_lbMenuMouseExited

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        lg.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbStatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbStatisticsMouseClicked
        c.show(pnChung, "Statistics");
        lbHienTai.setText("Statistics");
        HienThi();
    }//GEN-LAST:event_lbStatisticsMouseClicked

    private void lbInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInvoiceMouseClicked
        c.show(pnChung, "Invoice");
        lbHienTai.setText("Invoice");
        HienThi();
    }//GEN-LAST:event_lbInvoiceMouseClicked

    private void lbSupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSupplyMouseClicked
        c.show(pnChung, "Supply");
        lbHienTai.setText("Supply");
        HienThi();
    }//GEN-LAST:event_lbSupplyMouseClicked

    private void lbCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCustomerMouseClicked
        c.show(pnChung, "Customer");
        lbHienTai.setText("Customer");
        HienThi();
    }//GEN-LAST:event_lbCustomerMouseClicked

    private void lbProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProductMouseClicked
        c.show(pnChung, "Product");
        lbHienTai.setText("Product");
        HienThi();
    }//GEN-LAST:event_lbProductMouseClicked

    private void lbEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEmployeeMouseClicked
        c.show(pnChung, "Employee");
        lbHienTai.setText("Employee");
        HienThi();
    }//GEN-LAST:event_lbEmployeeMouseClicked

    private void lbInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInformationMouseClicked
        c.show(pnChung, "Information");
        lbHienTai.setText("Information");
        HienThi();
    }//GEN-LAST:event_lbInformationMouseClicked

    private void lbSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSupplierMouseClicked
        c.show(pnChung, "Supplier");
        lbHienTai.setText("Supplier");
        HienThi();
    }//GEN-LAST:event_lbSupplierMouseClicked

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered

    }//GEN-LAST:event_lbExitMouseEntered

    private void btExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportActionPerformed
        if(lbHienTai.getText().equals("Supplier")){
            SupplierBUS supplierBUS = new SupplierBUS();
            supplierBUS.ExportExcel();
            JOptionPane.showMessageDialog(this,"export excel file successfully");
            return;
        }
        if(lbHienTai.getText().equals("Employee")){
            EmployeeBUS employeeBUS = new EmployeeBUS();
            employeeBUS.ExportExcel();
            JOptionPane.showMessageDialog(this,"export excel file successfully");
            return;
        }
        if(lbHienTai.getText().equals("Product")){
            ProductBUS productBUS = new ProductBUS();
            productBUS.ExportExcel();
            JOptionPane.showMessageDialog(this,"export excel file successfully");
            return;
        }
        if(lbHienTai.getText().equals("Customer")){
            CustomerBUS customerBUS = new CustomerBUS();
            customerBUS.ExportExcel();
             JOptionPane.showMessageDialog(this,"export excel file successfully");
            return;
        }
         
        
    }//GEN-LAST:event_btExportActionPerformed

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home_Page hp = new Home_Page();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Design.MyButtonIcon btExport;
    private Design.MyButtonIcon btImport;
    private javax.swing.ButtonGroup buttonGroup1;
    private Design.MyLabel_IconRight lbCustomer;
    private Design.MyLabel_IconRight lbEmployee;
    private Design.MyLabel_Icon lbExit;
    private javax.swing.JLabel lbHienTai;
    private Design.MyLabel_IconRight lbInformation;
    private Design.MyLabel_IconRight lbInvoice;
    private Design.MyLabel_Icon lbLogo;
    private Design.MyLabel_IconRight lbLogout;
    private Design.MyLabel_Icon lbMenu;
    private Design.MyLabel_IconRight lbProduct;
    private Design.MyLabel_IconRight lbStatistics;
    private Design.MyLabel_IconRight lbSupplier;
    private Design.MyLabel_IconRight lbSupply;
    private javax.swing.JPanel pnChung;
    private javax.swing.JPanel pnHomePage;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnNen;
    private javax.swing.JPanel pnTieuDe;
    private javax.swing.JPanel pnToolBar;
    // End of variables declaration//GEN-END:variables
}
