
package GUI;

import BUS.ProductBUS;
import BUS.TypeBUS;
import DTO.ProductDTO;
import DTO.TypeDTO;
import Design.TableCustom;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ProductGUI extends javax.swing.JPanel {
    DefaultTableModel modelProduct;
    private ArrayList<ProductDTO> listProduct;
    private ProductBUS prodBUS = new ProductBUS();
    DefaultTableModel modelType;
    private ArrayList<TypeDTO> listType;
    private TypeBUS typeBUS = new TypeBUS();
   
    /**
     * Creates new form NewJPanel
     */
    public ProductGUI() {
        initComponents();
        TableCustom.apply(jScrollPane1, TableCustom.TableType.DEFAULT);
        modelProduct = (DefaultTableModel) tbTableProduct.getModel();
        prodBUS.readList();
        loadDataProduct();
        TableCustom.apply(jScrollPane8, TableCustom.TableType.DEFAULT);
        modelType= (DefaultTableModel) tbTableType.getModel();
        typeBUS.readList();
        loadDataType();
    }
    public void loadDataProduct(){
        listProduct = prodBUS.getListProduct();
        showAllProduct(listProduct);
    }
    public void loadSearch(String sql){
        listProduct = prodBUS.getSearch(sql);
        showAllProduct(listProduct);
    }
    public void loadDataType(){
        listType = typeBUS.getListType();
        showAllType(listType);
    }
    public void showAllType(ArrayList<TypeDTO> listtype){
        modelType.setRowCount(0);
        for(int i = 0; i < listtype.size();i++){
            modelType.addRow(new String []{
            listtype.get(i).getMaLoai(),
            listtype.get(i).getTenLoai(),
            });
        }
    }

    public void showAllProduct(ArrayList<ProductDTO> listProd){
        modelProduct.setRowCount(0);
        for(int i = 0; i < listProd.size();i++){
            modelProduct.addRow(new String []{
            listProd.get(i).getMaSP(),
            listProd.get(i).getTenSP(),
            listProd.get(i).getSoLuong(),
            listProd.get(i).getGiaNhapHang(),
            listProd.get(i).getGiaSanPham(),
            listProd.get(i).getMaLoai(),
            listProd.get(i).getMaNSX(),
            listProd.get(i).getIMG()
        
        
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panelBorder1 = new Design.PanelBorder();
        attribute3 = new Design.Attribute();
        txtMaSP = new Design.Text();
        attribute2 = new Design.Attribute();
        txtTenSP = new Design.Text();
        attribute4 = new Design.Attribute();
        txtSoLuong = new Design.Text();
        attribute6 = new Design.Attribute();
        txtGiaSP = new Design.Text();
        attribute7 = new Design.Attribute();
        txtMaNSX = new Design.Text();
        attribute5 = new Design.Attribute();
        txtMaLoai = new Design.Text();
        attribute1 = new Design.Attribute();
        lbHinhAnh = new Design.MyLabel_Icon();
        panelBorder3 = new Design.PanelBorder();
        btUpdateProduct = new Design.MyButtonIcon();
        btDeleteProduct = new Design.MyButtonIcon();
        btAddProduct = new Design.MyButtonIcon();
        txtNewProduct = new Design.MyButtonIcon();
        ckMaSP = new javax.swing.JCheckBox();
        ckTenSP = new javax.swing.JCheckBox();
        ckSoLuong = new javax.swing.JCheckBox();
        ckGiaNH = new javax.swing.JCheckBox();
        ckMaNSX = new javax.swing.JCheckBox();
        ckMaLoai = new javax.swing.JCheckBox();
        ckGiaSP = new javax.swing.JCheckBox();
        btSearch = new Design.MyButtonIcon();
        txtIMG = new Design.Text();
        attribute9 = new Design.Attribute();
        txtGiaNhapHang = new Design.Text();
        attribute10 = new Design.Attribute();
        panelBorder2 = new Design.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTableProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        panelBorder21 = new Design.PanelBorder();
        attribute60 = new Design.Attribute();
        txtMaloai = new Design.Text();
        attribute61 = new Design.Attribute();
        txtTenLoai = new Design.Text();
        panelBorder22 = new Design.PanelBorder();
        btDeleteType = new Design.MyButtonIcon();
        btAddType = new Design.MyButtonIcon();
        btUpdateProducer = new Design.MyButtonIcon();
        btNewType = new Design.MyButtonIcon();
        myButtonIcon2 = new Design.MyButtonIcon();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        panelBorder24 = new Design.PanelBorder();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbTableType = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder1.setBackground(new java.awt.Color(230, 230, 230));

        attribute3.setText("Mã sản phẩm");

        txtMaSP.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute2.setText("Tên sản phẩm");

        txtTenSP.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute4.setText("Số lượng");

        txtSoLuong.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute6.setText("Giá sản phẩm");

        txtGiaSP.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute7.setText("Mã nhà sản xuất");

        txtMaNSX.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute5.setText("Mã loại");

        txtMaLoai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute1.setText("Hình ảnh sản phẩm");

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));

        btUpdateProduct.setText("Update");
        btUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateProductActionPerformed(evt);
            }
        });

        btDeleteProduct.setText("Delete");
        btDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteProductActionPerformed(evt);
            }
        });

        btAddProduct.setText("Add");
        btAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProductActionPerformed(evt);
            }
        });

        txtNewProduct.setText("Clear");
        txtNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewProductActionPerformed(evt);
            }
        });

        ckMaSP.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckMaSP.setForeground(new java.awt.Color(0, 0, 0));
        ckMaSP.setText("Mã sản phẩm");

        ckTenSP.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckTenSP.setForeground(new java.awt.Color(0, 0, 0));
        ckTenSP.setText("Tên sản phẩm");

        ckSoLuong.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckSoLuong.setForeground(new java.awt.Color(0, 0, 0));
        ckSoLuong.setText("Số lượng");

        ckGiaNH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckGiaNH.setForeground(new java.awt.Color(0, 0, 0));
        ckGiaNH.setText("Giá nhập hàng");

        ckMaNSX.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckMaNSX.setForeground(new java.awt.Color(0, 0, 0));
        ckMaNSX.setText("Mã nhà sản xuất");

        ckMaLoai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckMaLoai.setForeground(new java.awt.Color(0, 0, 0));
        ckMaLoai.setText("Mã loại");

        ckGiaSP.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckGiaSP.setForeground(new java.awt.Color(0, 0, 0));
        ckGiaSP.setText("Giá sản phẩm");

        btSearch.setText("Search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder3Layout.createSequentialGroup()
                        .addComponent(btAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btUpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder3Layout.createSequentialGroup()
                        .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder3Layout.createSequentialGroup()
                                .addComponent(ckMaSP)
                                .addGap(24, 24, 24)
                                .addComponent(ckGiaNH)
                                .addGap(18, 18, 18)
                                .addComponent(ckGiaSP))
                            .addGroup(panelBorder3Layout.createSequentialGroup()
                                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckTenSP)
                                    .addComponent(ckSoLuong))
                                .addGap(18, 18, 18)
                                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckMaLoai)
                                    .addGroup(panelBorder3Layout.createSequentialGroup()
                                        .addComponent(ckMaNSX)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckMaSP)
                    .addComponent(ckGiaNH)
                    .addComponent(ckGiaSP))
                .addGap(18, 18, 18)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckTenSP)
                    .addComponent(ckMaNSX)
                    .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckSoLuong)
                    .addComponent(ckMaLoai))
                .addGap(18, 18, 18)
                .addComponent(txtNewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        txtIMG.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute9.setText("IMG");

        txtGiaNhapHang.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute10.setText("Giá nhập hàng");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attribute3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribute4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(attribute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaNSX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelBorder1Layout.createSequentialGroup()
                                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(attribute5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                                .addComponent(attribute9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(panelBorder1Layout.createSequentialGroup()
                                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGiaNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                                .addComponent(attribute10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(attribute6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(attribute7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attribute3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(attribute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attribute7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(attribute4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attribute5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attribute9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1150, 280));

        panelBorder2.setBackground(new java.awt.Color(230, 230, 230));

        tbTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá nhập hàng", "Giá sản phẩm", "Mã loại", "Mã nhà cung cấp", "Ảnh sản phẩm"
            }
        ));
        tbTableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTableProduct);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1158, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.add(panelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1170, 300));

        jTabbedPane1.addTab("Product", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelBorder21.setBackground(new java.awt.Color(200, 200, 200));

        attribute60.setText("Mã loại");

        txtMaloai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        attribute61.setText("Tên loại");

        txtTenLoai.setFont(new java.awt.Font("Dosis ExtraBold", 0, 15)); // NOI18N

        panelBorder22.setBackground(new java.awt.Color(255, 255, 255));

        btDeleteType.setText("Delete");
        btDeleteType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteTypeActionPerformed(evt);
            }
        });

        btAddType.setText("Add");
        btAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTypeActionPerformed(evt);
            }
        });

        btUpdateProducer.setText("Update");
        btUpdateProducer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateProducerActionPerformed(evt);
            }
        });

        btNewType.setText("Clear");
        btNewType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewTypeActionPerformed(evt);
            }
        });

        myButtonIcon2.setText("Search");

        jCheckBox8.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox8.setText("Mã loại");

        jCheckBox9.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox9.setText("Tên loại");

        javax.swing.GroupLayout panelBorder22Layout = new javax.swing.GroupLayout(panelBorder22);
        panelBorder22.setLayout(panelBorder22Layout);
        panelBorder22Layout.setHorizontalGroup(
            panelBorder22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder22Layout.createSequentialGroup()
                        .addComponent(jCheckBox9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBorder22Layout.createSequentialGroup()
                        .addGroup(panelBorder22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelBorder22Layout.createSequentialGroup()
                                .addComponent(jCheckBox8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(myButtonIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBorder22Layout.createSequentialGroup()
                                .addGroup(panelBorder22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btAddType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btNewType, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addComponent(btDeleteType, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btUpdateProducer, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        panelBorder22Layout.setVerticalGroup(
            panelBorder22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder22Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelBorder22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox8)
                    .addComponent(myButtonIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btNewType, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelBorder22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeleteType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUpdateProducer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBorder21Layout = new javax.swing.GroupLayout(panelBorder21);
        panelBorder21.setLayout(panelBorder21Layout);
        panelBorder21Layout.setHorizontalGroup(
            panelBorder21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(attribute60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribute61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaloai, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelBorder22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelBorder21Layout.setVerticalGroup(
            panelBorder21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder21Layout.createSequentialGroup()
                        .addComponent(attribute60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attribute61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelBorder24.setBackground(new java.awt.Color(230, 230, 230));

        tbTableType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ));
        tbTableType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTableTypeMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tbTableType);

        javax.swing.GroupLayout panelBorder24Layout = new javax.swing.GroupLayout(panelBorder24);
        panelBorder24.setLayout(panelBorder24Layout);
        panelBorder24Layout.setHorizontalGroup(
            panelBorder24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder24Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelBorder24Layout.setVerticalGroup(
            panelBorder24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder24Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(panelBorder21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(panelBorder24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Type", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateProductActionPerformed
        String MaSP = txtMaSP.getText();
        String TenSP = txtTenSP.getText();
        String SoLuong = txtSoLuong.getText();
        String GiaNH = txtGiaNhapHang.getText();
        String GiaSP = txtGiaSP.getText();
        String MaLoai = txtMaLoai.getText();
        String MaNSX = txtMaNSX.getText();
        String IMG = txtIMG.getText();
        ProductDTO product = new ProductDTO(MaSP, TenSP, SoLuong,GiaNH, GiaSP, MaLoai, MaNSX, IMG);
        prodBUS.update(product);
        loadDataProduct();
    }//GEN-LAST:event_btUpdateProductActionPerformed

    private void btDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteProductActionPerformed
        prodBUS.delete(txtMaSP.getText());
        loadDataProduct();
        JOptionPane.showMessageDialog(this, "Product removed!");
    }//GEN-LAST:event_btDeleteProductActionPerformed

    private void btAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProductActionPerformed
        if (txtMaSP.getText().trim().isEmpty()
            || txtTenSP.getText().trim().isEmpty()
            || txtSoLuong.getText().trim().isEmpty()
            ||txtGiaNhapHang.getText().trim().isEmpty()
            || txtGiaSP.getText().trim().isEmpty()
            || txtMaNSX.getText().trim().isEmpty()
            || txtIMG.getText().trim().isEmpty()
            || txtMaLoai.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please fill in customer information!");
            return;
        }
        String MaSP = txtMaSP.getText();
        String TenSP = txtTenSP.getText();
        String SoLuong = txtSoLuong.getText();
        String GiaNH = txtGiaNhapHang.getText();
        String GiaSP = txtGiaSP.getText();
        String MaLoai = txtMaLoai.getText();
        String MaNSX = txtMaNSX.getText();
        String IMG = txtIMG.getText();
        ProductDTO product = new ProductDTO(MaSP, TenSP, SoLuong,GiaNH, GiaSP, MaLoai, MaNSX, IMG);
        prodBUS.insert(product);
        loadDataProduct();
        JOptionPane.showMessageDialog(this, "Successfully added product!");
    }//GEN-LAST:event_btAddProductActionPerformed

    private void txtNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewProductActionPerformed
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtSoLuong.setText("");
        txtGiaNhapHang.setText("");
        txtGiaSP.setText("");
        txtMaLoai.setText("");
        txtMaNSX.setText("");
        txtIMG.setText("");
        txtMaSP.setEnabled(true);
        tbTableProduct.getSelectionModel().clearSelection(); //bỏ chọn Row trong JTable
    }//GEN-LAST:event_txtNewProductActionPerformed

    private void tbTableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTableProductMouseClicked
        int k = tbTableProduct.getSelectedRow();
        txtMaSP.setText(tbTableProduct.getModel().getValueAt(k, 0).toString());
        txtTenSP.setText(tbTableProduct.getModel().getValueAt(k, 1).toString());
        txtSoLuong.setText(tbTableProduct.getModel().getValueAt(k, 2).toString());
        txtGiaNhapHang.setText(tbTableProduct.getModel().getValueAt(k, 3).toString());
        txtGiaSP.setText(tbTableProduct.getModel().getValueAt(k, 4).toString());
        txtMaLoai.setText(tbTableProduct.getModel().getValueAt(k, 5).toString());
        txtMaNSX.setText(tbTableProduct.getModel().getValueAt(k, 6).toString());
        txtIMG.setText(tbTableProduct.getModel().getValueAt(k, 7).toString());
        txtMaSP.setEnabled(false);

    }//GEN-LAST:event_tbTableProductMouseClicked

    private void tbTableTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTableTypeMouseClicked
        int k = tbTableType.getSelectedRow();
        txtMaloai.setText(tbTableType.getModel().getValueAt(k, 0).toString());
        txtTenLoai.setText(tbTableType.getModel().getValueAt(k, 1).toString());
    }//GEN-LAST:event_tbTableTypeMouseClicked

    private void btNewTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewTypeActionPerformed
        txtMaloai.setText("");
        txtTenLoai.setText("");
        txtMaloai.setEnabled(true);
        tbTableType.getSelectionModel().clearSelection(); //bỏ chọn Row trong JTable
    }//GEN-LAST:event_btNewTypeActionPerformed
    
    private void btUpdateProducerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateProducerActionPerformed
        String MaLoai = txtMaloai.getText();
        String TenLoai = txtTenLoai.getText();
        TypeDTO type = new TypeDTO(MaLoai, TenLoai);
        typeBUS.update(type);
        loadDataType();
    }//GEN-LAST:event_btUpdateProducerActionPerformed

    private void btAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTypeActionPerformed
           if (txtMaloai.getText().trim().isEmpty() || txtTenLoai.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in type information!");
            return;
        }
        String MaLoai = txtMaloai.getText();
        String TenLoai = txtTenLoai.getText();
        TypeDTO type = new TypeDTO(MaLoai, TenLoai);
        typeBUS.insert(type);
        loadDataType();
        JOptionPane.showMessageDialog(this, "!");
    }//GEN-LAST:event_btAddTypeActionPerformed

    private void btDeleteTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteTypeActionPerformed
        typeBUS.delete(txtMaloai.getText());
        loadDataType();
        JOptionPane.showMessageDialog(this, "!");
    }//GEN-LAST:event_btDeleteTypeActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        String sql = "SELECT * FROM SANPHAM WHERE isDelete = 0"; 
        try{
            String MaSP = txtMaSP.getText();
            String TenSP = txtTenSP.getText();
            String MaLoai = txtMaLoai.getText();
            String MaNSX = txtMaNSX.getText();
            String SoLuong = txtSoLuong.getText();
            String GiaSP = txtGiaSP.getText();
            String GiaNH = txtGiaNhapHang.getText();
            if(ckMaSP.isSelected()){
                if(MaSP.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập mã sản phẩm cần tìm");
                    return;
                }
                    sql +=" AND MASP LIKE '%" + MaSP+ "%'";
            }
            if(ckTenSP.isSelected()){
                if(TenSP.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập tên sản phẩm cần tìm");
                    return;
                }
                    sql +=" AND TENSP LIKE '%" + TenSP + "%'";
            }
            if(ckMaLoai.isSelected()){
                if(MaLoai.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập mã loại cần tìm");
                    return;
                }
                    sql +=" AND MALOAI LIKE '%" + MaLoai+ "%'";
            }
            if(ckMaNSX.isSelected()){
                if(MaNSX.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập mã nhà sản xuất cần tìm");
                    return;
                }
                    sql +=" AND MALOAI LIKE '%" + MaNSX + "%'";
            }
            if(ckSoLuong.isSelected()){
                if(SoLuong.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập số lượng thấp nhất cần lọc");
                    return;
                }
                    sql +=" AND SOLUONG >= " + SoLuong + " AND SOLUONG <= 1000000000";  
            }
            if(ckGiaNH.isSelected()){
                if(GiaNH.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa giá nhập hàng thấp nhất cần lọc");
                    return;
                }
                    sql +=" AND GIANH >= " + GiaNH + " AND GIANH <= 1000000000"; 
            }
            if(ckGiaSP.isSelected()){
                 if(GiaSP.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa giá sản phẩm thấp nhất cần lọc");
                    return;
                }
                    sql +=" AND GIASP >= " + GiaSP + " AND GIASP <= 1000000000";    
            }
            loadSearch(sql);
        }  
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Design.Attribute attribute1;
    private Design.Attribute attribute10;
    private Design.Attribute attribute2;
    private Design.Attribute attribute3;
    private Design.Attribute attribute4;
    private Design.Attribute attribute5;
    private Design.Attribute attribute6;
    private Design.Attribute attribute60;
    private Design.Attribute attribute61;
    private Design.Attribute attribute7;
    private Design.Attribute attribute9;
    private Design.MyButtonIcon btAddProduct;
    private Design.MyButtonIcon btAddType;
    private Design.MyButtonIcon btDeleteProduct;
    private Design.MyButtonIcon btDeleteType;
    private Design.MyButtonIcon btNewType;
    private Design.MyButtonIcon btSearch;
    private Design.MyButtonIcon btUpdateProducer;
    private Design.MyButtonIcon btUpdateProduct;
    private javax.swing.JCheckBox ckGiaNH;
    private javax.swing.JCheckBox ckGiaSP;
    private javax.swing.JCheckBox ckMaLoai;
    private javax.swing.JCheckBox ckMaNSX;
    private javax.swing.JCheckBox ckMaSP;
    private javax.swing.JCheckBox ckSoLuong;
    private javax.swing.JCheckBox ckTenSP;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private Design.MyLabel_Icon lbHinhAnh;
    private Design.MyButtonIcon myButtonIcon2;
    private Design.PanelBorder panelBorder1;
    private Design.PanelBorder panelBorder2;
    private Design.PanelBorder panelBorder21;
    private Design.PanelBorder panelBorder22;
    private Design.PanelBorder panelBorder24;
    private Design.PanelBorder panelBorder3;
    private javax.swing.JTable tbTableProduct;
    private javax.swing.JTable tbTableType;
    private Design.Text txtGiaNhapHang;
    private Design.Text txtGiaSP;
    private Design.Text txtIMG;
    private Design.Text txtMaLoai;
    private Design.Text txtMaNSX;
    private Design.Text txtMaSP;
    private Design.Text txtMaloai;
    private Design.MyButtonIcon txtNewProduct;
    private Design.Text txtSoLuong;
    private Design.Text txtTenLoai;
    private Design.Text txtTenSP;
    // End of variables declaration//GEN-END:variables
}
