
package GUI;

import BUS.CTSupplyBUS;
import BUS.ProductBUS;
import BUS.SupplyBUS;
import DTO.CTSupplyDTO;
import DTO.InformationDTO;
import DTO.ProductDTO;
import DTO.SupplyDTO;
import Design.TableCustom;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class SupplyGUI extends javax.swing.JPanel {
    DefaultTableModel modelSupply;
    private SupplyBUS suBUS = new SupplyBUS();
    private ArrayList<SupplyDTO> listSupply;
   
    DefaultTableModel modelCTSupply;
    private CTSupplyBUS ctsuBUS = new CTSupplyBUS();
    private ArrayList<CTSupplyDTO> listCTSupply;
    
    private ProductBUS proBUS = new ProductBUS();
    private ArrayList<ProductDTO> listProduct;
    private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private int Sum = 0;
    private int SL;
    public SupplyGUI() {
        initComponents();
        TableCustom.apply(jScrollPane5, TableCustom.TableType.DEFAULT);
        modelSupply = (DefaultTableModel) tbTableSupply.getModel();
        suBUS.readList();
        loadDataSupply();
        TableCustom.apply(jScrollPane4, TableCustom.TableType.DEFAULT);
        modelCTSupply = (DefaultTableModel) tbTableCTSupply.getModel();
        ctsuBUS.readList();
        loadDataCTSuTheoMa("1");
        btXemPH.setSelected(true);
        txtMaSP.setEnabled(false);
        txtTenSP.setEnabled(false);
        txtGiaNH.setEnabled(false);
        btAdd.setEnabled(false);
        btDelete.setEnabled(false);
        proBUS.readList();
        loadDataProduct();
       
        
    }
    public void loadDataSupply(){
        listSupply = suBUS.getListSupply();
        showAllSupply(listSupply);
    }
     public void loadDataCTSuTheoMa(String MaNH){
        listCTSupply = ctsuBUS.getListCTInvoiceTheoMaHD(MaNH);     
        showCTSupplyTheoMa(listCTSupply);
    }
    public void loadDataProduct(){
        listProduct = proBUS.getListProduct();
    }
     public void loadSearch(String sql){
        listSupply = suBUS.getSearch(sql);
        showAllSupply(listSupply);
    }
    public void showAllSupply(ArrayList<SupplyDTO> listSup){
        modelSupply.setRowCount(0);
        for(int i = 0; i < listSup.size();i++){
            modelSupply.addRow(new String[]{
            listSup.get(i).getMaNH(),
            dateFormat.format(listSup.get(i).getNgayNhap()),
            listSup.get(i).getMaNV(),
            listSup.get(i).getMaNCC(),
            listSup.get(i).getTongTien()
            
            });
        }
    }
    public void showCTSupplyTheoMa(ArrayList<CTSupplyDTO> listCTSup){
        modelCTSupply.setRowCount(0);
        for(int i = 0; i < listCTSup.size();i++){
            modelCTSupply.addRow(new String []{
            listCTSup.get(i).getMaNH(),
            listCTSup.get(i).getMaSP(),
            listCTSup.get(i).getTenSP(),
            listCTSup.get(i).getGiaSP(),
            listCTSup.get(i).getSoLuong()

            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBorder11 = new Design.PanelBorder();
        panelBorder13 = new Design.PanelBorder();
        attribute40 = new Design.Attribute();
        attribute41 = new Design.Attribute();
        txtMaNH = new Design.Text();
        txtMaNV = new Design.Text();
        txtTongTien = new Design.Text();
        attribute42 = new Design.Attribute();
        attribute43 = new Design.Attribute();
        txtMaNCC = new Design.Text();
        attribute44 = new Design.Attribute();
        txtNgayNhap = new com.toedter.calendar.JDateChooser();
        btNCC = new Design.MyButton();
        panelBorder14 = new Design.PanelBorder();
        attribute45 = new Design.Attribute();
        attribute46 = new Design.Attribute();
        attribute47 = new Design.Attribute();
        attribute51 = new Design.Attribute();
        txtMaSP = new Design.Text();
        txtTenSP = new Design.Text();
        txtGiaNH = new Design.Text();
        txtSoLuong = new Design.Text();
        btSP = new Design.MyButton();
        panelBorder12 = new Design.PanelBorder();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbTableSupply = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbTableCTSupply = new javax.swing.JTable();
        panelBorder15 = new Design.PanelBorder();
        btNew = new Design.MyButtonIcon();
        btAdd = new Design.MyButtonIcon();
        btDelete = new Design.MyButtonIcon();
        btTaoPN = new javax.swing.JRadioButton();
        btXemPH = new javax.swing.JRadioButton();
        Print = new Design.MyButtonIcon();
        CkTimNgayTheoKhoang = new javax.swing.JCheckBox();
        btSearch = new Design.MyButtonIcon();
        NgayNhap = new javax.swing.JCheckBox();
        txtNgayBatDau = new com.toedter.calendar.JDateChooser();
        attribute1 = new Design.Attribute();
        ckMaNV = new javax.swing.JCheckBox();
        txtNgayKetThuc = new com.toedter.calendar.JDateChooser();
        ckMaNCC = new javax.swing.JCheckBox();
        ckMaNH = new javax.swing.JCheckBox();
        ckTongTien = new javax.swing.JCheckBox();
        btClear = new Design.MyButtonIcon();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder11.setBackground(new java.awt.Color(230, 230, 230));

        panelBorder13.setBackground(new java.awt.Color(153, 153, 153));

        attribute40.setText("Mã nhập hàng");

        attribute41.setText("Ngày nhập hàng");

        attribute42.setText("Mã nhân viên");

        attribute43.setText("Mã nhà cung cấp");

        attribute44.setText("Tổng tiền");

        btNCC.setText("...");
        btNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder13Layout = new javax.swing.GroupLayout(panelBorder13);
        panelBorder13.setLayout(panelBorder13Layout);
        panelBorder13Layout.setHorizontalGroup(
            panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder13Layout.createSequentialGroup()
                        .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attribute40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNH, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attribute41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attribute42, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(attribute43, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder13Layout.createSequentialGroup()
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(panelBorder13Layout.createSequentialGroup()
                .addComponent(attribute44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBorder13Layout.setVerticalGroup(
            panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attribute40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribute41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attribute42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attribute43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attribute44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelBorder14.setBackground(new java.awt.Color(153, 153, 153));

        attribute45.setText("Mã sản phẩm");

        attribute46.setText("Tên sản phẩm");

        attribute47.setText("Giá nhập hàng");

        attribute51.setText("Số lượng");

        btSP.setText("...");
        btSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder14Layout = new javax.swing.GroupLayout(panelBorder14);
        panelBorder14.setLayout(panelBorder14Layout);
        panelBorder14Layout.setHorizontalGroup(
            panelBorder14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGiaNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder14Layout.createSequentialGroup()
                        .addGroup(panelBorder14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attribute51, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attribute46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBorder14Layout.createSequentialGroup()
                        .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBorder14Layout.setVerticalGroup(
            panelBorder14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attribute45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attribute46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attribute47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(txtGiaNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attribute51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout panelBorder11Layout = new javax.swing.GroupLayout(panelBorder11);
        panelBorder11.setLayout(panelBorder11Layout);
        panelBorder11Layout.setHorizontalGroup(
            panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder13, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorder14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder11Layout.setVerticalGroup(
            panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(panelBorder11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, 350));

        panelBorder12.setBackground(new java.awt.Color(153, 153, 153));

        tbTableSupply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhập hàng", "Ngày nhập hàng", "Mã nhân viên", "Mã nhà cung cấp", "Tổng tiền"
            }
        ));
        tbTableSupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTableSupplyMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbTableSupply);

        tbTableCTSupply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhập hàng", "Mã sản phẩm", "Tên sản phẩm", "Giá nhập hàng", "Số lượng"
            }
        ));
        tbTableCTSupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTableCTSupplyMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbTableCTSupply);
        if (tbTableCTSupply.getColumnModel().getColumnCount() > 0) {
            tbTableCTSupply.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout panelBorder12Layout = new javax.swing.GroupLayout(panelBorder12);
        panelBorder12.setLayout(panelBorder12Layout);
        panelBorder12Layout.setHorizontalGroup(
            panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder12Layout.setVerticalGroup(
            panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelBorder12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 630, 630));

        panelBorder15.setBackground(new java.awt.Color(153, 153, 153));

        btNew.setText("New");
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        buttonGroup1.add(btTaoPN);
        btTaoPN.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        btTaoPN.setForeground(new java.awt.Color(0, 0, 0));
        btTaoPN.setText("Tạo phiếu nhập");
        btTaoPN.setContentAreaFilled(false);
        btTaoPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaoPNActionPerformed(evt);
            }
        });

        buttonGroup1.add(btXemPH);
        btXemPH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        btXemPH.setForeground(new java.awt.Color(0, 0, 0));
        btXemPH.setText("Xem phiếu nhập");
        btXemPH.setBorderPainted(true);
        btXemPH.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btXemPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemPHActionPerformed(evt);
            }
        });

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        CkTimNgayTheoKhoang.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        CkTimNgayTheoKhoang.setForeground(new java.awt.Color(0, 0, 0));
        CkTimNgayTheoKhoang.setText("Tìm ngày theo khoảng");

        btSearch.setText("Search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        NgayNhap.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        NgayNhap.setForeground(new java.awt.Color(0, 0, 0));
        NgayNhap.setText("Ngày lập");

        attribute1.setText("đến");

        ckMaNV.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckMaNV.setForeground(new java.awt.Color(0, 0, 0));
        ckMaNV.setText("Mã nhân viên");

        ckMaNCC.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckMaNCC.setForeground(new java.awt.Color(0, 0, 0));
        ckMaNCC.setText("Mã nhà cung cấp");

        ckMaNH.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckMaNH.setForeground(new java.awt.Color(0, 0, 0));
        ckMaNH.setText("Mã nhập hàng");

        ckTongTien.setFont(new java.awt.Font("Dosis ExtraBold", 0, 13)); // NOI18N
        ckTongTien.setForeground(new java.awt.Color(0, 0, 0));
        ckTongTien.setText("Tổng tiền");

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder15Layout = new javax.swing.GroupLayout(panelBorder15);
        panelBorder15.setLayout(panelBorder15Layout);
        panelBorder15Layout.setHorizontalGroup(
            panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder15Layout.createSequentialGroup()
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckMaNH)
                            .addComponent(ckMaNCC)
                            .addComponent(ckMaNV))
                        .addGap(55, 55, 55)
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CkTimNgayTheoKhoang)
                            .addComponent(NgayNhap)
                            .addComponent(ckTongTien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE))
                    .addGroup(panelBorder15Layout.createSequentialGroup()
                        .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelBorder15Layout.createSequentialGroup()
                                .addComponent(btXemPH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBorder15Layout.createSequentialGroup()
                                .addComponent(btTaoPN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btNew, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBorder15Layout.createSequentialGroup()
                        .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attribute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBorder15Layout.setVerticalGroup(
            panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder15Layout.createSequentialGroup()
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btTaoPN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXemPH))
                    .addGroup(panelBorder15Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btNew, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder15Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder15Layout.createSequentialGroup()
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckMaNH)
                            .addComponent(NgayNhap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckTongTien)
                            .addComponent(ckMaNCC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CkTimNgayTheoKhoang)
                            .addComponent(ckMaNV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(attribute1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );

        add(panelBorder15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 510, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void btNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNCCActionPerformed
        DialogSupplier ds = new DialogSupplier();
        ds.setVisible(true);
        String s = ds.getMaNhaCungCap();
        txtMaNCC.setText(s);

    }//GEN-LAST:event_btNCCActionPerformed

    private void btSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSPActionPerformed
        if(txtMaNCC.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa có mã nhà cung cấp");
            return;
        }
        String MaNCC = txtMaNCC.getText();
        DialogProductNH dp = new DialogProductNH(MaNCC);
        dp.setVisible(true);
        String m = dp.getMaSanPham();
        txtMaSP.setText(m);
        String t = dp.getTenSanPham();
        txtTenSP.setText(t);
        String g = dp.getGiaNhapHang();
        txtGiaNH.setText(g);
        dp.loadDataProduct();


    }//GEN-LAST:event_btSPActionPerformed

    private void tbTableSupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTableSupplyMouseClicked
           int k = tbTableSupply.getSelectedRow();
        txtMaNH.setText(tbTableSupply.getModel().getValueAt(k, 0).toString());
        txtMaNCC.setText(tbTableSupply.getModel().getValueAt(k, 3).toString());
        txtMaNV.setText(tbTableSupply.getModel().getValueAt(k, 2).toString());
        txtTongTien.setText(tbTableSupply.getModel().getValueAt(k, 4).toString());
        String dateString = tbTableSupply.getModel().getValueAt(k,1).toString();
        try {
            Date d = dateFormat.parse(dateString);
            txtNgayNhap.setDate(d);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        String MaHD = txtMaNH.getText();
        loadDataCTSuTheoMa(MaHD);
    }//GEN-LAST:event_tbTableSupplyMouseClicked

    private void tbTableCTSupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTableCTSupplyMouseClicked
        int k = tbTableCTSupply.getSelectedRow();
        txtMaSP.setText(tbTableCTSupply.getModel().getValueAt(k, 1).toString());
        txtTenSP.setText(tbTableCTSupply.getModel().getValueAt(k, 2).toString());
        txtGiaNH.setText(tbTableCTSupply.getModel().getValueAt(k, 3).toString());       
        txtSoLuong.setText(tbTableCTSupply.getModel().getValueAt(k, 4).toString());
    }//GEN-LAST:event_tbTableCTSupplyMouseClicked

    private void btTaoPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoPNActionPerformed
        tbTableSupply.setEnabled(false);
        tbTableSupply.getSelectionModel().clearSelection(); //bỏ chọn Row trong JTable
        btAdd.setEnabled(true);
        btDelete.setEnabled(true);

    }//GEN-LAST:event_btTaoPNActionPerformed

    private void btXemPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemPHActionPerformed
        tbTableSupply.setEnabled(true);
        btAdd.setEnabled(false);
        btDelete.setEnabled(false);

    }//GEN-LAST:event_btXemPHActionPerformed
    public void setSoLuong(CTSupplyDTO ct){
        for(ProductDTO pro : listProduct){
            if(pro.getMaSP().equals(ct.getMaSP())){
                SL = Integer.parseInt(pro.getSoLuong()) + Integer.parseInt(ct.getSoLuong());
                ProductDTO p = new ProductDTO(
                        pro.getMaSP(), 
                        pro.getTenSP(), 
                        String.valueOf(SL), 
                        pro.getGiaNhapHang(), 
                        pro.getGiaSanPham(), 
                        pro.getMaLoai(), 
                        pro.getMaNSX(), 
                        pro.getIMG());
                proBUS.update(p);
            }
        }
    }
    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try{
            String MaNH = txtMaNH.getText();
            String MaNCC = txtMaNCC.getText();
            String MaNV = txtMaNV.getText();
            Date NgayLap = txtNgayNhap.getDate();
            String TongTien = txtTongTien.getText();
            SupplyDTO in = new SupplyDTO(MaNH, MaNCC, MaNV, NgayLap, TongTien);
            suBUS.insert(in);
            loadDataSupply();

            for(CTSupplyDTO x : listCTSupply){
                ctsuBUS.insert(x);
                setSoLuong(x);
            }
            
            modelCTSupply.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Tạo phiếu nhập hàng thành công thành công");
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        InformationDTO io = new InformationDTO();
        loadDataSupply();
        int MaNH = Integer.parseInt(listSupply.get(listSupply.size() -1).getMaNH()) + 1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        txtMaNH.setText(String.valueOf(MaNH));
        txtMaNV.setText(io.getMaNV());
        txtMaNCC.setText("");
        txtTongTien.setText("");
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtGiaNH.setText("");
        txtSoLuong.setText("");
        modelCTSupply.setRowCount(0);
        listCTSupply.clear();
        Sum = 0;
    }//GEN-LAST:event_btNewActionPerformed
     public CTSupplyDTO KT_CT(){
        for(CTSupplyDTO ct : listCTSupply){
            if(ct.getMaSP().equals(txtMaSP.getText())){
               return ct;
            }
       }
        return null;
    }
    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        listCTSupply.remove(KT_CT());
        showCTSupplyTheoMa(listCTSupply);
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if(txtMaNH.getText().trim().isEmpty()
           ||txtMaSP.getText().trim().isEmpty()
           || txtTenSP.getText().trim().isEmpty()
           || txtGiaNH.getText().trim().isEmpty()
           || txtSoLuong.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in product information!");
            return;
        }
        String MaNH = txtMaNH.getText();
        String MaSP = txtMaSP.getText();
        String TenSP = txtTenSP.getText();
        String GiaNH = txtGiaNH.getText();
        String Soluong = txtSoLuong.getText();
        CTSupplyDTO ct = new CTSupplyDTO(MaNH, MaSP, TenSP, GiaNH, Soluong);

        listCTSupply.add(ct);
        showCTSupplyTheoMa(listCTSupply);
        Sum += Integer.parseInt(GiaNH) * Integer.parseInt(Soluong);
        txtTongTien.setText(String.valueOf(Sum));
        
    }//GEN-LAST:event_btAddActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        String sql ="SELECT * FROM NHAPHANG WHERE 1 = 1";
        try{
            String MaNH = txtMaNH.getText();
            String MaNCC= txtMaNCC.getText();
            String MaNV = txtMaNV.getText();
            Date dateNgayNhap = txtNgayNhap.getDate();
            Date dateNgayBatDau = txtNgayBatDau.getDate();
            Date dateNgayKetThuc = txtNgayKetThuc.getDate();
            String NgayLap = "";
            String NgayBatDau ="";
            String NgayKetThuc = "";
            String TongTien = txtTongTien.getText();
            if(ckMaNH.isSelected()){
                if(MaNH.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập mã nhập hàng cần tìm");
                    return;
                }
                sql +=" AND MANH LIKE " + MaNH ;
            }
            if(ckMaNCC.isSelected()){
                if(MaNCC.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập mã nhà cung cấp cần tìm");
                    return;
                }
                sql +=" AND MANCC LIKE '%" + MaNCC + "%'";
            }
            if(ckMaNV.isSelected()){
                if(MaNV.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập mã nhân viên cần tìm");
                    return;
                }
                sql +=" AND MANV LIKE '%" + MaNV + "%'";
            }
            if(NgayNhap.isSelected() && dateNgayNhap != null){
                NgayLap = dateFormat.format(dateNgayNhap);
                sql +=" AND NGAYNHAP = '" + NgayLap + "'";
            }
            if(CkTimNgayTheoKhoang.isSelected() && dateNgayBatDau != null && dateNgayKetThuc != null){
                NgayBatDau = dateFormat.format(dateNgayBatDau);
                NgayKetThuc = dateFormat.format(dateNgayKetThuc);
                sql +=" AND NGAYNHAP BETWEEN '" + NgayBatDau +"' AND '" + NgayKetThuc +"'";
            }
            if(ckTongTien.isSelected()){
                if(TongTien.trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Chưa nhập tổng tiền thấp nhất cần lọc");
                    return;
                }
                sql +=" AND TONGTIEN >= " + TongTien + " AND TONGTIEN <= 1000000000";
            }
            loadSearch(sql);
        }
        catch(Exception ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btSearchActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CkTimNgayTheoKhoang;
    private javax.swing.JCheckBox NgayNhap;
    private Design.MyButtonIcon Print;
    private Design.Attribute attribute1;
    private Design.Attribute attribute40;
    private Design.Attribute attribute41;
    private Design.Attribute attribute42;
    private Design.Attribute attribute43;
    private Design.Attribute attribute44;
    private Design.Attribute attribute45;
    private Design.Attribute attribute46;
    private Design.Attribute attribute47;
    private Design.Attribute attribute51;
    private Design.MyButtonIcon btAdd;
    private Design.MyButtonIcon btClear;
    private Design.MyButtonIcon btDelete;
    private Design.MyButton btNCC;
    private Design.MyButtonIcon btNew;
    private Design.MyButton btSP;
    private Design.MyButtonIcon btSearch;
    private javax.swing.JRadioButton btTaoPN;
    private javax.swing.JRadioButton btXemPH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckMaNCC;
    private javax.swing.JCheckBox ckMaNH;
    private javax.swing.JCheckBox ckMaNV;
    private javax.swing.JCheckBox ckTongTien;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private Design.PanelBorder panelBorder11;
    private Design.PanelBorder panelBorder12;
    private Design.PanelBorder panelBorder13;
    private Design.PanelBorder panelBorder14;
    private Design.PanelBorder panelBorder15;
    private javax.swing.JTable tbTableCTSupply;
    private javax.swing.JTable tbTableSupply;
    private Design.Text txtGiaNH;
    private Design.Text txtMaNCC;
    private Design.Text txtMaNH;
    private Design.Text txtMaNV;
    private Design.Text txtMaSP;
    private com.toedter.calendar.JDateChooser txtNgayBatDau;
    private com.toedter.calendar.JDateChooser txtNgayKetThuc;
    private com.toedter.calendar.JDateChooser txtNgayNhap;
    private Design.Text txtSoLuong;
    private Design.Text txtTenSP;
    private Design.Text txtTongTien;
    // End of variables declaration//GEN-END:variables
}
